=== ZoeMcFife/Matura_5AHITM/Schriftlich/Fachtheorie/INSY/INSY_Brachinger_4AHITM/Aufgaben/XML/01_XML_Aufgaben_2024-04-11/kino.dtd
<!ELEMENT kino (standort, filme, spielplan)>

<!ELEMENT standort (saal+)>

<!ELEMENT saal (name)>

<!ATTLIST saal kennung ID #REQUIRED>

<!ELEMENT name (#PCDATA)>

<!ELEMENT filme (film+)>

<!ELEMENT regie (#PCDATA)>

<!ELEMENT darsteller (#PCDATA)>

<!ELEMENT film (name, regie, darsteller, darsteller+)>

<!ATTLIST film nr ID #REQUIRED>

<!ELEMENT spielplan (auffuehrung*)>

<!ELEMENT auffuehrung (ort*)>

<!ELEMENT ort (#PCDATA)>

<!ATTLIST auffuehrung datum CDATA #REQUIRED>

<!ATTLIST auffuehrung film IDREF #REQUIRED>

<!ATTLIST ort uhrzeit CDATA #REQUIRED>

<!ATTLIST ort saal IDREF #REQUIRED>

=== ZoeMcFife/Matura_5AHITM/Schriftlich/Fachtheorie/INSY/INSY_Brachinger_4AHITM/Aufgaben/XML/01_XML_Aufgaben_2024-04-11/kino.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kino SYSTEM "kino.dtd">
<kino>
	<standort>
		<saal kennung="am">
			<name>Audi Max</name>
		</saal>
		<saal kennung="s2">
			<name>Saal 2</name>
		</saal>
		<saal kennung="s3">
			<name>Saal 3</name>
		</saal>
		<saal kennung="s4">
			<name>Saal 4</name>
		</saal>
	</standort>
	<filme>
		<film nr="f123">
			<name>Krieg der Sterne IV</name>
			<regie>George Lucas</regie>
			<darsteller>Mark Hamill</darsteller>
			<darsteller>Harrison Ford</darsteller>
		</film>
		<film nr="f124">
			<name>Der Herr der Ringe - Die Gefährten</name>
			<regie>Peter Jackson</regie>
			<darsteller>Elijah Wood</darsteller>
			<darsteller>Ian McKellen</darsteller>
		</film>
		<film nr="f125">
			<name>Der Pate</name>
			<regie>Francis Ford Coppola</regie>
			<darsteller>Marlon Brando</darsteller>
			<darsteller>Al Pacino</darsteller>
		</film>
	</filme>
	<spielplan>
		<auffuehrung datum="2013-10-22" film="f123">
			<ort uhrzeit="22:00" saal="am"/>
			<ort uhrzeit="22:30" saal="s4"/>
		</auffuehrung>
		<auffuehrung datum="2013-10-22" film="f124">
			<ort uhrzeit="19:15" saal="am"/>
			<ort uhrzeit="21:00" saal="s2"/>
			<ort uhrzeit="20:45" saal="s3"/>
		</auffuehrung>
		<auffuehrung datum="2013-10-22" film="f125">
			<ort uhrzeit="20:15" saal="s3"/>
		</auffuehrung>
		<auffuehrung datum="2013-10-23" film="f123"/>
	</spielplan>
</kino>
